import React from 'react';
import { useForm, Controller } from 'react-hook-form';

const TaskForm = () => {
  const { control, handleSubmit, watch } = useForm();

  // This function will be called when the form is submitted
  const onSubmit = (data) => {
    console.log(data);
    // You can handle form submission logic here
  };

  const selectedRole = watch('role');

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <div>
        <label>Full Name:</label>
        <Controller
          name="fullName"
          control={control}
          rules={{ required: 'Full name is required' }}
          defaultValue=""
          render={({ field, fieldState }) => (
            <div>
              <input {...field} />
              {fieldState.error && <span>{fieldState.error.message}</span>}
            </div>
          )}
        />
      </div>

      <div>
        <label>Email:</label>
        <Controller
          name="email"
          control={control}
          rules={{
            required: 'Email is required',
            pattern: {
              value: /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/,
              message: 'Invalid email format',
            },
          }}
          defaultValue=""
          render={({ field, fieldState }) => (
            <div>
              <input {...field} />
              {fieldState.error && <span>{fieldState.error.message}</span>}
            </div>
          )}
        />
      </div>

      <div>
        <label>Role:</label>
        <Controller
          name="role"
          control={control}
          defaultValue="admin"
          render={({ field }) => (
            <select {...field}>
              <option value="admin">Admin</option>
              <option value="member">Member</option>
            </select>
          )}
        />
      </div>

      {selectedRole === 'member' && (
        <>
          <div>
            <label>Hourly Rate:</label>
            <Controller
              name="hourlyRate"
              control={control}
              defaultValue=""
              render={({ field }) => <input {...field} />}
            />
          </div>

          <div>
            <label>Autogenerated Password:</label>
            <Controller
              name="autogenerated"
              control={control}
              defaultValue=""
              render={({ field }) => (
                <input
                  {...field}
                  disabled
                  value={watch('email').split('@')[0]} // Autogenerated value based on the email
                />
              )}
            />
          </div>
        </>
      )}

      <button type="submit">Submit</button>
    </form>
  );
};

export default TaskForm;
