import React from 'react';
import { useForm, Controller } from 'react-hook-form';
import { useNavigate } from 'react-router-dom';

import './styles.css';

const UserForm = () => {
  const { control, handleSubmit, watch } = useForm();
  const navigate = useNavigate();

  // This function will be called when the form is submitted
  const onSubmit = (data) => {
    console.log(data);
    // You can handle form submission logic here
  };

  const selectedRole = watch('role');

  return (
    <div>
      <div className='head-title'>Create a user</div>
      <form id='user-form' onSubmit={handleSubmit(onSubmit)}>
        <div className='row'>
          <div className='input-wrap'>
            <label>Full Name:</label>
            <Controller
              name="fullName"
              control={control}
              rules={{ required: 'Full name is required' }}
              defaultValue=""
              render={({ field, fieldState }) => (
                <>
                  <input {...field} />
                  {fieldState.error && <span className='error'>{fieldState.error.message}</span>}
                </>
              )}
            />
          </div>

          <div className='input-wrap'>
            <label>Email:</label>
            <Controller
              name="email"
              control={control}
              rules={{
                required: 'Email is required',
                pattern: {
                  value: /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/,
                  message: 'Invalid email format',
                },
              }}
              defaultValue=""
              render={({ field, fieldState }) => (
                <>
                  <input {...field} />
                  {fieldState.error && <span className='error'>{fieldState.error.message}</span>}
                </>
              )}
            />
          </div>
        </div>

        <div className='row'>
          <div className='input-wrap'>
            <label>Role:</label>
            <Controller
              name="role"
              control={control}
              defaultValue="admin"
              render={({ field }) => (
                <select className='select' {...field}>
                  <option value="admin">Admin</option>
                  <option value="member">Member</option>
                </select>
              )}
            />
          </div>

          <div className='input-wrap'>
            <label>Password: (auto-gen)</label>
            <Controller
              name="autogenerated"
              control={control}
              defaultValue=""
              render={({ field }) => {
                let watcher = watch('email')?.split('@')[0];

                return (
                  <input
                    {...field}
                    disabled
                    value={watcher ? `${watcher}@123` : watcher} // Autogenerated value based on the email
                  />
                );
              }}
            />
          </div>
        </div>
        {selectedRole === 'member' && (
          <div className='row'>
            <div className='input-wrap'>

            </div>
            <div className='input-wrap'>
              <label>Hourly Rate:</label>
              <Controller
                name="hourlyRate"
                control={control}
                defaultValue=""
                render={({ field }) => <input {...field} />}
              />
            </div>
          </div>
        )}

        <div className='row btn-wrap'>
          <div className='input-wrap btn'>
            <button type="submit">Submit</button>
          </div>

          <div className='input-wrap btn' onClick={() => navigate('/members')}>
            <button className='cancel'>Cancel</button>
          </div>
        </div>
      </form>
    </div>
  );
};

export default UserForm;
